site_name: ResilientDB Quickstart Guide
site_url: https://gopuman.github.io/resilientdb-quickstart/
site_author: 'ResilientDB'

# Theme configuration
theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  logo: 'images/resilientdb.svg'  
  palette:
    - scheme: default
      primary: 'blue'
      accent: 'teal'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: 'blue'
      accent: 'teal'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

# Extra CSS and JavaScript
extra_css:
  - 'stylesheets/extra.css'  # Custom CSS file
extra_javascript:
  - 'js/custom.js'  # Custom JavaScript file (optional)

# Site navigation
nav:
  - Home: index.md
  - Blog: blog.md
  - Installation: installation.md
  - Usage:
      - ResilientDB: usage/resilientdb.md
      - PythonSDK: usage/pythonsdk.md
      - ResDBORM: usage/resdborm.md
      - Smart-Contracts CLI: usage/smart-contracts-cli.md
      - Smart-Contracts GraphQL: usage/smart-contracts-graphql.md
      - ResVault: usage/resvault.md
  - API Reference: api.md
  - Contributors: contributors.md
  - About: about.md

# Plugins configuration
plugins:
  - search
  - include-markdown:
      rewrite-relative-urls: true
  # - blogging  # Uncomment if using a blogging plugin
  # - mkdocstrings  # Uncomment if using API documentation

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

# Extra configurations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ResilientEcosystem
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/YourProject
  meta:
    - name: description
      content: "ResilientDB Quickstart Guide and Documentation"
    - name: keywords
      content: "ResilientDB, blockchain, documentation, quickstart"

# Site directory configuration
site_dir: site  # Output directory for built site

# Repository configuration
repo_name: 'ResilientEcosystem/resilientdb-quickstart'
repo_url: 'https://github.com/ResilientEcosystem/resilientdb-quickstart'
edit_uri: 'edit/main/docs/'
